# Generated by Django 5.1.1 on 2024-09-23 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=10)),
                ('semester', models.IntegerField()),
                ('roll_number', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='StudentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rollno', models.CharField(max_length=100, unique=True)),
                ('attendance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sem3cgpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('question1', models.TextField()),
                ('question2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
