# Generated by Django 5.1.1 on 2024-10-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_remove_mentorshipdata_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshipdata',
            name='year',
            field=models.CharField(default='SE', max_length=10),
            preserve_default=False,
        ),
    ]
