# Generated by Django 5.1.1 on 2024-09-20 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_mentor_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='role',
        ),
    ]
