# Generated by Django 5.1.1 on 2024-10-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_student_token_student_token_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentform',
            old_name='sem3cgpa',
            new_name='semcgpa',
        ),
        migrations.AddField(
            model_name='studentform',
            name='atte_ise1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='studentform',
            name='atte_mse',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='studentform',
            name='cts',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='studentform',
            name='ise1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='studentform',
            name='mse',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='studentform',
            name='question10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='question11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='question3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='question4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='question5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='question6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='question7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='question8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='question9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentform',
            name='question1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentform',
            name='question2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
