# Generated by Django 5.1.1 on 2024-10-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0003_rename_sem3cgpa_studentform_semcgpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentform',
            name='counseling_dates',
            field=models.TextField(blank=True, null=True),
        ),
    ]
