# Generated by Django 5.1.1 on 2024-09-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0003_remove_mentor_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('section', models.CharField(max_length=1)),
                ('science_marks', models.IntegerField()),
                ('english_marks', models.IntegerField()),
                ('history_marks', models.IntegerField()),
                ('maths_marks', models.IntegerField()),
            ],
        ),
    ]
