# Generated by Django 5.1.1 on 2024-10-18 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0003_mentorshipdata_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='student',
            field=models.ForeignKey(default='152', on_delete=django.db.models.deletion.CASCADE, to='mentor.mentorshipdata'),
            preserve_default=False,
        ),
    ]
