# Generated by Django 5.1.1 on 2024-09-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0004_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rollno', models.CharField(max_length=100, unique=True)),
                ('attendance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sem3cgpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('question1', models.TextField()),
                ('question2', models.TextField()),
            ],
        ),
    ]
