# Generated by Django 5.1.1 on 2024-10-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0005_studentform_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('roll_number', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=10)),
                ('faculty_mentor', models.CharField(blank=True, max_length=255, null=True)),
                ('be_student_mentor', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
