# Generated by Django 5.1.1 on 2024-09-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0005_student_form'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_Form',
            new_name='StudentForm',
        ),
    ]
