# Generated by Django 5.1.1 on 2024-10-19 03:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0005_studentform_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentform',
            name='profile_picture',
            field=models.ImageField(blank=True, default='', upload_to='profile_pictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
            preserve_default=False,
        ),
    ]
