# Generated by Django 5.1.1 on 2024-10-01 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0006_mentorshipdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorshipdata',
            name='sr_no',
        ),
    ]
