# Generated by Django 5.1.1 on 2024-09-22 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0006_rename_student_form_studentform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentform',
            name='name',
        ),
    ]
