# Generated by Django 5.1.1 on 2024-09-22 16:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0007_remove_studentform_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentform',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
