# Generated by Django 5.1.1 on 2024-10-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0009_session_mentor_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshipdata',
            name='sem',
            field=models.IntegerField(default='3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentorshipdata',
            name='year',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
