# Generated by Django 5.1.1 on 2024-10-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0011_alter_mentorshipdata_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorshipdata',
            name='sem',
            field=models.IntegerField(null=True),
        ),
    ]
