# Generated by Django 5.1.1 on 2024-10-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0012_alter_mentorshipdata_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshipdata',
            name='batch',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
