# Generated by Django 5.1.1 on 2024-10-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0017_session_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshipdata',
            name='year',
            field=models.CharField(default='SE', max_length=10),
            preserve_default=False,
        ),
    ]
