# Generated by Django 5.1.1 on 2024-10-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0018_mentorshipdata_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshipdata',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mentorshipdata',
            name='token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
