# Generated by Django 5.1.1 on 2024-10-17 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0019_mentorshipdata_token_mentorshipdata_token_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atte_ise1', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('atte_mse', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('attendance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cts', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('ise1', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('mse', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('semcgpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('mentorship_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor.mentorshipdata')),
            ],
        ),
    ]
