# Generated by Django 5.1.1 on 2024-10-17 10:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0020_student1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfollowupform',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studentform',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
